### ISSUE TITLE
The server can not start

### ISSUE THREAD

**Issue by jimmystlr** [nickm980/smallville#34]
Hi, I encounter some issues when trying to start the smallville server with the command you provided in README.

After building the server project with mvn package, I tried to start the server with command:
java -jar target/smallville-1.3.0.jar --api-key xxx

And get the following error logs:
Exception in thread "main" io.javalin.util.JavalinException: io.javalin.util.JavalinException: Static resource directory with path: './' does not exist. Depending on your setup, empty folders might not get copied to classpath.
	at io.javalin.Javalin.start(Javalin.java:186)
	at io.javalin.Javalin.start(Javalin.java:148)
	at io.github.nickm980.smallville.api.SmallvilleServer.start(SmallvilleServer.java:44)
	at io.github.nickm980.smallville.Smallville.startServer(Smallville.java:74)
	at io.github.nickm980.smallville.Smallville.main(Smallville.java:44)
Caused by: io.javalin.util.JavalinException: Static resource directory with path: './' does not exist. Depending on your setup, empty folders might not get copied to classpath.
	at io.javalin.jetty.ConfigurableHandler.getResourceBase(JettyResourceHandler.kt:112)
	at io.javalin.jetty.ConfigurableHandler.<init>(JettyResourceHandler.kt:76)
	at io.javalin.jetty.JettyResourceHandler.init(JettyResourceHandler.kt:31)
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:80)
	at io.javalin.Javalin.start(Javalin.java:171)
	... 4 more

BTW, some tests in the java project are broken, like MemoryStreamTest.

**Comment by nickm980** [comment]
Does #35 solve the issues? I removed the static files since I moved the dashboard - don't think they are needed anymore
